version: '3'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - PGUSER=${POSTGRES_USER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: "-p ${POSTGRES_PORT}"
    healthcheck:
      test: "pg_isready -p ${POSTGRES_PORT} -d ${POSTGRES_DB}"
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
